services:
  - type: web
    name: techverse-improve
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: GITHUB_TOKEN
        sync: false   # You must set this manually in Render dashboard
      - key: MICROSOFT_ACCESS_TOKEN
        sync: false   # Optional - set only if SharePoint is used
